version: "3"
services:
    db:
      image: mongo:latest
      ports:
        - 27017:27017
    data-extractor:
      build:
        dockerfile: ./dockerfile/Dockerfile.extractor
      environment:
        ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
        MONGODB_NAME: ${MONGODB_NAME}
        action_url: ${action_url}
        book_url: ${book_url}
      ports:
        - 5001:5001
      volumes:
        - ./dataset:/usr/src/app/dataset
    data-provider:
      build:
        dockerfile: ./dockerfile/Dockerfile.provider
      environment:
        ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
        MONGODB_NAME: ${MONGODB_NAME}
      ports:
        - 5002:5002
    model:
      build:
        dockerfile: ./dockerfile/Dockerfile.model-provider
      environment:
        ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
        MONGODB_NAME: ${MONGODB_NAME}
      ports:
        - 5000:5000

    api-gateway:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 8080:8080


