FROM python:3.10-slim

WORKDIR /usr/src/app
# RUN apt-get update 

COPY requirements_extractor.txt .
RUN pip install -r requirements_extractor.txt

COPY dataset ./dataset
COPY data_extractor.py .

CMD ["python", "data_extractor.py"]
